# Generated by Django 5.2.4 on 2025-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
